services:

  # -------- PostgreSQL --------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline_net

  # -------- MinIO --------
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - pipeline_net

  # -------- NiFi --------
  nifi:
    image: apache/nifi:1.26.0
    container_name: nifi
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_JARS_DIR: /opt/nifi/nifi-custom-lib 
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/Public/pipeline_UITS_BD/data/input:/opt/nifi/input
      - /c/Users/Public/nifi-drivers:/opt/nifi/nifi-custom-lib   
      - nifi_data_conf:/opt/nifi/nifi-current/conf
      - nifi_data_db:/opt/nifi/nifi-current/database_repository
      - nifi_data_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_data_content:/opt/nifi/nifi-current/content_repository
      - nifi_data_provenance:/opt/nifi/nifi-current/provenance_repository
    networks:
      - pipeline_net

  # -------- Kafka --------
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Identifiants du nœud
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller

      # Listeners internes et externes
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      # Liaison interne du cluster (contrôleur)
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Autoriser le PLAINTEXT (pas SSL)
      ALLOW_PLAINTEXT_LISTENER: "yes"

      # Chemin des logs
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data

    volumes:
      - kafka_data:/bitnami/kafka/data

    networks:
      - pipeline_net


  spark-master:
    image: bitnami/spark:3.3.2-debian-11-r10
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark-apps:/opt/spark-apps
      - C:/Users/Public/pipeline_UITS_BD/jars:/opt/spark/jars
      - spark_data:/opt/spark-data
    networks:
      - pipeline_net

  spark-worker-1:
    image: bitnami/spark:3.3.2-debian-11-r10
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./spark-apps:/opt/spark-apps
      - C:/Users/Public/pipeline_UITS_BD/jars:/opt/spark/jars
      - spark_data:/opt/spark-data
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    networks:
      - pipeline_net

  spark-worker-2:
    image: bitnami/spark:3.3.2-debian-11-r10
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./spark-apps:/opt/spark-apps
      - C:/Users/Public/pipeline_UITS_BD/jars:/opt/spark/jars
      - spark_data:/opt/spark-data
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    networks:
      - pipeline_net


  # -------- Airflow --------
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: custom-airflow:latest
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__FERNET_KEY: "Y6JZngIfTbGuvaUPbJdBktb13HKGvNedFwRJ3fDbzPI="
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/mydb
      AIRFLOW__WEBSERVER__SECRET_KEY: "cle_airflow_partagee_2025"
      HADOOP_CONF_DIR: /opt/airflow/hadoop_conf
    depends_on:
      - postgres
      - spark-master
      - minio
      - kafka
    ports:
      - "8084:8080"
    volumes:
      - airflow_logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./spark-apps:/opt/airflow/spark-apps 
      - ./core-site.xml:/opt/airflow/hadoop_conf/core-site.xml
      - C:/Users/Public/pipeline_UITS_BD/jars:/opt/airflow/jars
    command: webserver
    networks:
      - pipeline_net
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: custom-airflow:latest
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres
      - spark-master
      - minio
      - kafka
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__FERNET_KEY: "Y6JZngIfTbGuvaUPbJdBktb13HKGvNedFwRJ3fDbzPI="
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/mydb
      AIRFLOW__WEBSERVER__SECRET_KEY: "cle_airflow_partagee_2025"
      HADOOP_CONF_DIR: /opt/airflow/hadoop_conf
    volumes:
      - airflow_logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./spark-apps:/opt/airflow/spark-apps 
      - ./core-site.xml:/opt/airflow/hadoop_conf/core-site.xml
      - C:/Users/Public/pipeline_UITS_BD/jars:/opt/airflow/jars
    command: scheduler
    networks:
      - pipeline_net

  # -------- Superset --------
  superset:
    image: apache/superset:2.1.0   # version stable
    container_name: superset
    environment:
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "secret_key_1234"
      DATABASE_URL: postgresql+psycopg2://admin:admin123@postgres:5432/mydb

      SUPERSET_DATABASE_URI: postgresql+psycopg2://admin:admin123@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    volumes:
      - superset_data:/app/superset_home
    networks:
      - pipeline_net


# -------- Volumes --------
volumes:
  postgres_data:
  minio_data:
  airflow_logs:
  superset_data:
  nifi_data_conf:
  nifi_data_db:
  nifi_data_flowfile:
  nifi_data_content:
  nifi_data_provenance:
  kafka_data:
  spark_data:

# -------- Network --------
networks:
  pipeline_net:
    driver: bridge
